version: '3.8'

services:
  # Бэкенд (Spring Boot)
  backend:
    build: ./library
    env_file: ./library/.env
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL-AUTO: validate

  # Фронтенд (React)
  frontend:
    build: ./library-ui
    ports:
      - "3000:80"  # 80 - порт nginx внутри контейнера
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080  # Для доступа к бэкенду
